# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heidir Royyan Firdaus
email: heidirrf@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  
#twitter_username: julianreif
github_username: yocheidir
minimal_mistakes_skin: contrast # dirt # air # default
search: false
repository: yocheidir/yocheidir.github.io

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Heidir Royyan Firdaus"
  avatar : "/assets/images/heidir1.jpeg"
  bio    : "Bachelor of Economics from Airlangga University"
  links:    
    - label: "CV"
      icon: "fa fa-fw fa-file-pdf"
      url: "/cv/cv_new.pdf"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yocheidir"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:heidirrf@gmail.com"
    - label: "Phone"
      icon: "fas fa-phone"
      url: "tel:+62 81294688772"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/heidir_royyan_firdaus/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/yocheidir"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/share/1CRpw1yC9X/"
    - label: "Facebook"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/heidirrf"

footer:
  links:

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
